### ISSUE TITLE
Special handling for "type" property

### ISSUE THREAD

**Issue by matthchr** [Azure/k8s-infra#156]
We are currently handling the `type` property for resources as any other property, but in reality this doesn't make sense.

Instead, `type` should get special handling and get turned into a constant - it doesn't really make sense for customers to have to specify type.

**Comment by Porges** [comment]
In general, any fields that have type of "enum with one value" shouldn’t be part of the spec, we should elide them and just emit during JSON serialization (and check the values on deserialization).

**Comment by matthchr** [comment]
This is fixed by #213
