### ISSUE TITLE
Investigate replacing go/ast with dave/dst

### ISSUE THREAD

**Issue by babbageclunk** [Azure/k8s-infra#254]
Our AsType methods have a number of hacks to try to get the generated code looking the way we'd like, particularly around placement of comments and whitespace. These are needed because the go/ast handling for comments/whitespace is not well suited for code generation - positioning is done with byte offsets on the file, which doesn't yet exist in our case.

https://github.com/dave/dst is an alternative Go AST implementation that attaches comments and whitespace to code elements, so it's more likely that it would let us get code looking the way we want without hacks. It wasn't used initially because it looked inactive, but it has been active lately so it would be worth trying it out in a spike.

**Comment by Porges** [comment]
Completed by #336
