### ISSUE TITLE
Support dynamic delay in generic controller

### ISSUE THREAD

**Issue by matthchr** [Azure/k8s-infra#263]
When we go to delay while we're monitoring creates and deletes, we should have a way to look at the resource, determine when its state was last changed (time delta), and then compute the next delay based on how long it's taken already.

Something like, if it's taken 30m already, delay another 3m, if it's taken 5m delay another 30s.

**Comment by Porges** [comment]
We should also use the `Retry-After` header that can be returned by ARM.

**Comment by Porges** [comment]
Note that controller-runtime already implements exponential backoff for requeues or after errors, see: https://stuartleeks.com/posts/error-back-off-with-controller-runtime/

**Comment by matthchr** [comment]
@porges should we just close this now?

**Comment by Porges** [comment]
@matthchr I'm happy to.
