### ISSUE TITLE
Remove helper method `TypeAsTypeObject()`

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/k8s-infra#335]
The method `TypeAsTypeObject()` is a generic unwrapping method that is likely to become a problem in future because it unwraps everything, which is unlikely to be what's needed. There's a high chance that someone modifying it to work in one location would introduce subtle bugs affection other usage.

Solution: Remove it completely, refactoring current usage sites to do the right thing for their context.

It is currently only used in a couple of places.

**Comment by Porges** [comment]
This appears done.

**Comment by theunrepentantgeek** [comment]
Removed in PR #309
