### ISSUE TITLE
Resources with multiple owners

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/k8s-infra#359]
We need resources to have a single owner for the controller to work - but it appears that some resources have multiple owners (see table below). Discovered during other testing. 

Given that the majority (all?) of these are plural vs singular names, we may be able to resolve these easily; definitely need to address before alpha though.

| Owner Was | Changed to | # Times |
| ------ | ----- | ----- |
| Accounts | Account | 8
| ApplicationGateways | ApplicationGateway | 1
| AssessmentProjects | AssessmentProject | 3
| AssessmentProjectsGroups | AssessmentProjectsGroup | 1
| AutomationAccounts | AutomationAccount | 15
| BatchAccounts | BatchAccount | 4
| BatchAccountsApplications | BatchAccountsApplication | 2
| CertificateOrders | CertificateOrder | 1
| DatabaseAccountsApisDatabases | DatabaseAccountsApisDatabase | 3
| DatabaseAccountsApisDatabasesCollections | DatabaseAccountsApisDatabasesCollection | 1
| DatabaseAccountsApisDatabasesContainers | DatabaseAccountsApisDatabasesContainer | 1
| DatabaseAccountsApisDatabasesGraphs | DatabaseAccountsApisDatabasesGraph | 1
| DatabaseAccountsApisKeyspaces | DatabaseAccountsApisKeyspace | 2
| DatabaseAccountsApisKeyspacesTables | DatabaseAccountsApisKeyspacesTable | 1
| DatabaseAccountsApisTables | DatabaseAccountsApisTable | 1
| Domains | Domain | 2
| ExpressRouteCircuits | ExpressRouteCircuit | 42
| ExpressRouteCircuitsPeerings | ExpressRouteCircuitsPeering | 19
| ExpressRouteCrossConnections | ExpressRouteCrossConnection | 19
| ExpressRouteGateways | ExpressRouteGateway | 10
| Factories | Factory  | 6
| FirewallPolicies | FirewallPolicy | 9
| FrontDoors | FrontDoor | 1
| Galleries | Gallery | 2
| GalleriesImages | GalleriesImage | 2
| HostGroups | HostGroup | 2
| HostingEnvironments | HostingEnvironment | 1
| IotHubs | IotHub | 3
| JobCollections | JobCollection | 2
| Labs | Lab | 19
| LabsUsers | LabsUser | 3
| LabsVirtualmachines | LabsVirtualmachine | 1
| LoadBalancers | LoadBalancer | 16
| ManagedClusters | ManagedCluster | 1
| Managers | Manager | 7
| ManagersDevicesBackupPolicies | ManagersDevicesBackupPolicy | 1
| ManagersDevicesFileservers | ManagersDevicesFileserver | 1
| ManagersDevicesIscsiservers | ManagersDevicesIscsiserver | 1
| ManagersDevicesVolumeContainers | ManagersDevicesVolumeContainer | 1
| MediaServices | MediaService | 2
| MediaServicesAssets | MediaServicesAsset | 1
| MediaServicesLiveEvents | MediaServicesLiveEvent | 1
| MediaServicesTransforms | MediaServicesTransform | 1
| Namespaces | Namespace | 29
| NamespacesEventhubs | NamespacesEventhub | 6
| NamespacesHybridConnections | NamespacesHybridConnection | 2
| NamespacesNotificationHubs | NamespacesNotificationHub | 3
| NamespacesQueues | NamespacesQueue | 2
| NamespacesTopics | NamespacesTopic | 4
| NamespacesTopicsSubscriptions | NamespacesTopicsSubscription | 1
| NamespacesWcfRelays | NamespacesWcfRelay | 2
| NetAppAccounts | NetAppAccount | 2
| NetAppAccountsCapacityPools | NetAppAccountsCapacityPool | 2
| NetAppAccountsCapacityPoolsVolumes | NetAppAccountsCapacityPoolsVolume | 2
| NetworkExperimentProfiles | NetworkExperimentProfile | 1
| NetworkInterfaces | NetworkInterface  | 15
| NetworkSecurityGroups | NetworkSecurityGroup | 27
| NetworkVirtualAppliances | NetworkVirtualAppliance | 1
| NetworkWatchers | NetworkWatcher | 28
| PrivateDnsZones | PrivateDnsZone | 1
| PrivateEndpoints | PrivateEndpoint | 1
| PrivateLinkServices | PrivateLinkService | 10
| Profiles | Profile  | 2
| ProfilesEndpoints | ProfilesEndpoint | 4
| ProvisioningServices | ProvisioningService | 1
| Redis | Redi | 5
| Registrations | Registration | 1
| Registries | Registry | 2
| RouteFilters | RouteFilter | 3
| RouteTables | RouteTable | 27
| Servers | Server | 26
| ServersDatabases | ServersDatabase | 7
| ServersDatabasesDataMaskingPolicies | ServersDatabasesDataMaskingPolicy | 1
| ServiceApis | ServiceApi | 25
| ServiceApisDiagnostics | ServiceApisDiagnostic | 2
| ServiceApisIssues | ServiceApisIssue | 6
| ServiceApisOperations | ServiceApisOperation | 6
| ServiceDiagnostics | ServiceDiagnostic | 2
| ServiceEndpointPolicies | ServiceEndpointPolicy | 11
| ServiceGroups | ServiceGroup | 4
| ServiceNotifications | ServiceNotification | 6
| ServiceProducts | ServiceProduct | 14
| Sites | Site | 11
| SitesSlots | SitesSlot | 6
| SitesSlotsVirtualNetworkConnections | SitesSlotsVirtualNetworkConnection | 1
| SitesVirtualNetworkConnections | SitesVirtualNetworkConnection | 1
| StorageAccounts | StorageAccount | 13
| StorageAccountsBlobServices | StorageAccountsBlobService | 4
| StorageAccountsBlobServicesContainers | StorageAccountsBlobServicesContainer | 5
| StorageAccountsFileServices | StorageAccountsFileService | 1
| StorageAccountsQueueServices | StorageAccountsQueueService | 1
| StorageAccountsTableServices | StorageAccountsTableService | 1
| Streamingjobs | Streamingjob | 4
| Vaults | Vault | 3
| VaultsBackupFabricsProtectionContainers | VaultsBackupFabricsProtectionContainer | 1
| VaultsReplicationFabrics | VaultsReplicationFabric | 3
| VaultsReplicationFabricsReplicationProtectionContainers | VaultsReplicationFabricsReplicationProtectionContainer | 3
| VirtualHubs | VirtualHub | 11
| VirtualMachineScaleSets | VirtualMachineScaleSet | 5
| VirtualMachines | VirtualMachine | 54
| VirtualRouters | VirtualRouter | 8
| VirtualWans | VirtualWan | 3
| VpnGateways | VpnGateway | 13
| Workspaces | Workspace | 9
| WorkspacesExperiments | WorkspacesExperiment | 1

**Comment by matthchr** [comment]
@theunrepentantgeek - Can you clarify how exactly this shows up in the code, and/or what the impact is on the controller/resource?

I took a look at a few of the examples you shared (types with an owner of BatchAccount such as Pool, etc) and all of them seem to correctly refer to `BatchAccount` as the owner.

For example from `batch_accounts_pool_types_gen.go`:
```
type BatchAccountsPools_Spec struct {

	// +kubebuilder:validation:Required
	Owner genruntime.KnownResourceReference `group:"microsoft.batch.infra.azure.com" json:"owner" kind:"BatchAccount"`
}
```

This matches with the name of the type generated in `batch_account_types_gen.go`

Can you clarify how the issue shows up in the code, and/or if it's an issue not with the generated code but how we're making the mappings in memory (i.e. de-pluralization is applied late or something?)

**Comment by theunrepentantgeek** [comment]
If I remember correctly, I added some code to detect when the owner of a type was _changed_ during the generation process (hence the column names "Was" and "Changed to").

But "if I remember correctly" is key ... I need to reconstruct my thinking there.

**Comment by matthchr** [comment]
Let's sync up on this?

If the type name was changed (due to depluralization), then presumably it's correct that the owners name also changes to match?

**Comment by matthchr** [comment]
I synced up with @theunrepentantgeek on this and he shared this snippet which he had been using to detect these changes:
```
func (objectType *ObjectType) WithProperty(property *PropertyDefinition) *ObjectType {
    // Create a copy of objectType to preserve immutability
    result := objectType.copy()

    if property.propertyName == "Owner" {
        if existing, ok := result.properties[property.propertyName]; ok {
            klog.Warningf("Overwriting Owner: %v with %v", existing, property)
        }
    }

    result.properties[property.propertyName] = property

    return result
}
```

I ran the generator myself with that snippet enabled and the only output I saw was:
```
W0106 11:06:28.399809   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc011c7eea0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc011c7eea0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:32.816313   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc011c7eea0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc011c7eea0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:37.090594   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc015dd8520 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc015dd8520 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:38.014376   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc015dd8520 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc015dd8520 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:39.030725   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc0112e29e0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc0112e29e0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:40.115572   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc0112e29e0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc0112e29e0 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:41.347625   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc007417c60 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc007417c60 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:42.128625   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc007417c60 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc007417c60 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:43.790967   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc011a94100 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc011a94100 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
W0106 11:09:44.540458   10915 object_type.go:336] Overwriting Owner: &{Owner 0xc011a94100 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]} with &{Owner 0xc011a94100 A read-only property that identifies who created this interface endpoint. false map[json:[owner omitempty]]}
```

When I dug into these by putting a breakpoint on the log line and investigating what caused them I realized that they were for fields named "Owner" which were not created by us, instead they are fields named "Owner" that are part of the Swagger specification (of type `string` or `*string`), so I don't think they're of any concern.

I didn't observe a large number of renames like suggested above, nor did I notice any renames related to depluralization (which should be happening in the depluralization pipeline stage on the `Resource.Owner` field, not on a property called "Owner" of an ObjectType).

**Comment by theunrepentantgeek** [comment]
Huh. Weird. I'll try to circle back and reconstruct what I was doing when I noticed this. If I can't reproduce, will close the issue.

**Comment by theunrepentantgeek** [comment]
Closing as this is a non-issue. All of the renames identified above took place during the de-pluralization stage of the pipeline. 😊 

See [PR#364](https://github.com/Azure/k8s-infra/pull/364) for a fix to pluralization for Redis.
