### ISSUE TITLE
Improvements to astmodel object heirarchy

### ISSUE THREAD

**Issue by matthchr** [Azure/k8s-infra#97]
Not all of these have to be done, just a list of ideas to help simplify our lives:
1. Move `RelatedDefinitions()` to the `Definition` interface
2. Should `DefinitionName` really implement `Type`?
3. Improve `Function`/`FunctionDefinition` relationship with the rest of the astmodel types (This may partially be accomplished by 1 and 2 above)

**Comment by theunrepentantgeek** [comment]
#1: included in PR #101 - was part of some cleanup I did to fix the generated files.

**Comment by matthchr** [comment]
Resolving this as George suggested that having `Definition` work for `Function` was a bad idea to begin with, updated #80 to implement his suggestion, and @theunrepentantgeek already has item 1 in a PR.
